@url = http://localhost:5555
### create discount
POST {{url}}/discounts
Content-Type: application/json

{
    "Id":"8de5ce73-bf81-4398-8ad0-9b532dfc7d3e",
    "customerId": "82ee54ce-8169-9842-b578-9549e2db300c",
    "code": "PROMO",
    "percentage": 40
}